### PR TITLE
feat(): support ios/md attribute of ion-icon

### PR DESCRIPTION
**Pull request by rdlabo**
Support  ios/md attribute:

```html
<ion-icon name="logo-ionic" ios="add" md="remove"></ion-icon>
```

### CODE REVIEW

**Comment by sean-perkins** [comment]
@rdlabo thank you for the contribution, you are amazing! Would you be able to rebase this feature branch against the latest to resolve the merge conflict?

**Comment by rdlabo** [comment]
@sean-perkins  Thanks for checking, I've merged the main branch and resolved the conflicts.
Please check this.

**Review by sean-perkins — APPROVED** [review]
Fantastic work as always! Greatly appreciate you!

I'll merge this tonight, but will cut a release hopefully tomorrow between meetings.

**Comment by rdlabo** [comment]
Thanks for the merge. This is all the behavior I want to make better for now.

I look forward to the day when EXPERIMENTAL is removed from this tool and more people will use it.

**Pull request merged**
